### ISSUE TITLE
Meet boot error at enabling flarum-store-group

### ISSUE THREAD

**Issue by realybin** [zxy19/flarum-store-group#1]
I installed `xypp/store`.
Following are my phpinfo and the log printed in the file.
```
PHP 8.2.18 (cli) (built: Apr 11 2024 14:41:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.18, Copyright (c), by Zend Technologies
```
```
Next Flarum\Extension\Exception\ExtensionBootError: Experienced an error while booting extension: Store Group.

Error occurred while applying an extender of type: Xypp\Store\Extend\StoreItemProvider. in /opt/flarum/vendor/flarum/core/src/Extension/Extension.php:143
Stack trace:
#0 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(390): Flarum\Extension\Extension->extend()
#1 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#2 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#3 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#4 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#5 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#6 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#7 /opt/flarum/vendor/flarum/core/src/Http/Server.php(59): Flarum\Foundation\InstalledSite->bootApp()
#8 /opt/flarum/vendor/flarum/core/src/Http/Server.php(36): Flarum\Http\Server->safelyBootAndGetHandler()
#9 /opt/flarum/public/index.php(26): Flarum\Http\Server->listen()
#10 {main}  
```

**Comment by zxy19** [comment]
The problem was caused by a filename, and since windows is case insensitive, the case change commit was accidentally unsuccessful.

Fixed, thanks for the feedback.
